# Generated by Django 4.2 on 2025-04-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('bounty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_path', models.CharField(max_length=255)),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_address', models.TextField(blank=True, null=True)),
                ('reporter_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
